version: "3"

services:
  flyway:
    image: dhoer/flyway:alpine
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=password migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
